services:
  web:
    build: .
    depends_on:
      db:
        condition: service_healthy
        restart: true
  db:
    image: h2database/h2
    container_name: h2
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/h2:/h2data
    environment:
      - H2_DATABASE_FILE=java-filmorate
      - H2_USER=sa
      - H2_PASSWORD=password
    healthcheck:
      test: pg_isready -q -d $$H2_DATABASE_FILE -U $$H2_USER
      timeout: 5s
      interval: 5s
      retries: 10

