
services:
  db:
    image: h2database/h2
    container_name: h2
    ports:
      - "8082:8082"
    volumes:
      - ./volumes/h2:/h2data
    environment:
      - H2_DATABASE_FILE=h2db
      - H2_USER=h2user
      - H2_PASSWORD=h2password
    healthcheck:
      test: pg_isready -q -d H2_DATABASE_FILE -U H2_USER
      timeout: 5s
      interval: 5s
      retries: 10