CREATE TABLE IF NOT EXISTS my_users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL,
    login VARCHAR(50) NOT NULL,
    birthday DATE
);

CREATE TABLE IF NOT EXISTS films (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    description VARCHAR(200) NOT NULL,
    releaseDate TIMESTAMP,
    duration INTEGER,
    like INTEGER,
    genre_id INTEGER REFERENCES genre (id) ON DELETE CASCADE,
    rating_id INTEGER REFERENCES rating (id) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS genre (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre VARCHAR(50)
);


CREATE TABLE IF NOT EXISTS rating (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rating VARCHAR(5)
);


CREATE TABLE IF NOT EXISTS status (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status VARCHAR(20)
);

create table if not exists userLikes (
user_id int references USERS(user_id),
film_id int references FILMS(film_id ),
PRIMARY KEY (user_id,film_id)
);

create table if not exists friends (
user_id int not null references my_users,
friend_id int not null references my_users,
PRIMARY KEY (user_id,friend_id)
);


